apiVersion: v1
kind: Service
metadata:
  name: text-to-speech-service
spec:
  type: NodePort
  selector:
    app: text-to-speech
  ports:
    - protocol: TCP
      port: 5501
      targetPort: 5501
      nodePort: 30087
